apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: target-custom-cuda-notebook 
  namespace: edhat-ods-applications
spec:
  source:
    type: Git
    git:
      uri: https://github.com/tnscorcoran/rhoai-custom-image.git
    contextDir: helm
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Containerfile
      from:
        kind: ImageStreamTag  
        name: source-cuda-notebook:latest
  output:
    to:
      kind: ImageStreamTag
      name: target-custom-cuda-notebook:latest
  triggers:
  - type: ImageChange