apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-builder
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-builder
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops